// ============================================================
// FILE: src/pages/Terms.jsx
// ============================================================
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-tavern-dark" style={{
      backgroundImage: 'radial-gradient(circle, rgba(255,255,255,0.03) 1px, transparent 1px)',
      backgroundSize: '28px 28px',
    }}>
      <div className="max-w-3xl mx-auto px-4 py-16 sm:py-24">
        <div className="text-center mb-12">
          <p className="text-tavern-accent text-xs font-bold uppercase tracking-[0.3em] mb-3">Legal</p>
          <h1 className="text-3xl sm:text-4xl font-black text-white mb-4">Terms of Service</h1>
          <p className="text-white/25 text-xs">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>

        <div className="space-y-8 text-sm text-white/50 leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using MLBB Tavern (&quot;the Site&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Site.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. Nature of the Service</h2>
            <div className="bg-white/[0.03] border border-white/[0.06] rounded-xl p-5 mb-4">
              <p className="text-white/70 font-medium leading-relaxed">
                MLBB Tavern is a <span className="text-tavern-accent font-bold">bulletin board</span>. We do not employ pilots, we do not own sold accounts, and we are not responsible for transactions between users. All interactions, trades, and arrangements are made solely between users at their own risk.
              </p>
            </div>
            <p>The Site provides community boards, AI-powered game predictions, bracket tools, and esports player cards. These tools are provided &quot;as is&quot; without warranty of any kind.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. User Conduct</h2>
            <ul className="list-disc list-outside ml-5 space-y-2 text-white/40">
              <li>You are responsible for all content you post.</li>
              <li>No spam, scams, harassment, hate speech, or sexually explicit content.</li>
              <li>No sharing of personal information of others without consent.</li>
              <li>No attempts to circumvent security measures, rate limits, or access controls.</li>
              <li>No use of bots, scrapers, or automated tools to interact with the Site.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">4. Buy & Sell and Pilot Services</h2>
            <ul className="list-disc list-outside ml-5 space-y-2 text-white/40">
              <li>All transactions on the Buy & Sell and Pilot Services boards are between users only.</li>
              <li>MLBB Tavern does not act as an escrow, guarantor, or intermediary in any transaction.</li>
              <li>We do not verify the legitimacy of accounts, items, or services offered by users.</li>
              <li>If you are scammed, report the user via the report button. We may ban the offending account at our discretion.</li>
              <li><strong className="text-white/60">You assume all risk</strong> when engaging in any transaction on the Site.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">5. AI Predictions</h2>
            <p>Game predictions are generated by AI and are for <strong className="text-white/60">entertainment purposes only</strong>. They do not guarantee any match outcome. The free tier is limited to {3} predictions per day. Abuse of the prediction system (e.g., creating multiple accounts to bypass limits) will result in a ban.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">6. Moderation</h2>
            <ul className="list-disc list-outside ml-5 space-y-2 text-white/40">
              <li>Admins may pin, unpin, edit, or delete any content at their discretion.</li>
              <li>Admins may ban or suspend accounts for violations of these Terms.</li>
              <li>Admin decisions are final. No appeals process is provided.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>User-posted content remains the property of the poster. By posting, you grant MLBB Tavern a non-exclusive, worldwide, royalty-free license to display that content on the Site.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">8. Mobile Legends: Bang Bang Disclaimer</h2>
            <div className="bg-white/[0.03] border border-white/[0.06] rounded-xl p-5">
              <p className="text-white/70 leading-relaxed">
                MLBB Tavern is a <strong className="text-white">fan-made community tool</strong> and is <strong className="text-white">not affiliated with, endorsed by, or connected to</strong> Moonton, Shanghai Moonton Technology Co., Ltd., or any subsidiary. Mobile Legends: Bang Bang and all related assets are trademarks of Moonton.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">9. Limitation of Liability</h2>
            <p>MLBB Tavern and its developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Site, including but not limited to: financial losses from transactions, inaccurate AI predictions, or loss of data.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Site after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <div className="pt-8 border-t border-white/5 text-center">
            <p className="text-white/15 text-xs">Questions? Reach out through the Site or our community channels.</p>
            <Link to="/feed" className="inline-block mt-4 text-white/20 hover:text-white/50 text-sm transition-colors">
              ← Back to Feed
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}